/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./App.jsx",
    "./main.jsx",
    "./Pages/**/*.{js,jsx,ts,tsx}",
    "./Components/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#757c7b",
        "secondary-dim": "#515359",
        "primary": "#3f5f92",
        "on-error": "#fff7f6",
        "on-tertiary-fixed-variant": "#54536f",
        "on-secondary-fixed": "#3d3f45",
        "on-background": "#2d3433",
        "tertiary-fixed": "#d9d7f8",
        "on-primary-fixed": "#1c3f70",
        "inverse-surface": "#0c0f0e",
        "error-dim": "#4e0309",
        "surface-dim": "#d4dcda",
        "tertiary-container": "#d9d7f8",
        "secondary": "#5d5f65",
        "on-primary-container": "#315284",
        "on-tertiary": "#fbf7ff",
        "secondary-fixed": "#e2e2e9",
        "on-tertiary-container": "#4b4a65",
        "surface-variant": "#dde4e3",
        "primary-dim": "#325385",
        "surface-bright": "#f9f9f8",
        "secondary-container": "#e2e2e9",
        "background": "#f9f9f8",
        "surface-container-high": "#e4e9e8",
        "on-primary": "#f7f7ff",
        "on-primary-fixed-variant": "#3c5c8f",
        "tertiary-fixed-dim": "#cbc9e9",
        "primary-fixed-dim": "#c0d5ff",
        "primary-fixed": "#d6e3ff",
        "error": "#9f403d",
        "surface-tint": "#3f5f92",
        "on-secondary-fixed-variant": "#5a5b61",
        "inverse-primary": "#9abaf3",
        "surface-container-low": "#f2f4f3",
        "outline-variant": "#adb3b2",
        "on-tertiary-fixed": "#383751",
        "primary-container": "#d6e3ff",
        "on-secondary": "#f8f8ff",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#9c9d9c",
        "on-surface": "#2d3433",
        "secondary-fixed-dim": "#d3d4db",
        "tertiary-dim": "#51506c",
        "on-error-container": "#752121",
        "surface-container": "#ebeeed",
        "on-surface-variant": "#5a6060",
        "on-secondary-container": "#505257",
        "tertiary": "#5d5c78",
        "error-container": "#fe8983",
        "surface-container-highest": "#dde4e3",
        "surface": "#f9f9f8"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Public Sans"],
        "body": ["Newsreader"],
        "label": ["Public Sans"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
